# This is a basic workflow to help you get started with Actions
name: Deploy

# Controls when the workflow will run
on:
  # manual trigger
  # workflow_dispatch:

  #auto trigger
  push:
    branches:
    - main # use build branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest-8
          standalone: true

      # install & build
      - name: Install and Build
        run: |
          pnpm install
          pnpm run linux-build

      # deploy & use github-pages-deploy action ( gh-pages )
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: release
          folder: ./build
          github_token: ${{ secrets.GITHUB_TOKEN }}
