# This is a basic workflow to help you get started with Actions
name: Deploy

# Controls when the workflow will run
on:
  push:
    branches:
      - develop # 빌드할 브랜치
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.9.0'

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
